### ISSUE TITLE
FusionCMS 9.1.1 - Error on frontend

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [Karitoswow/character_tools#2]
After installing this Module and open it in the frontend then this error appearing.

![image](https://github.com/user-attachments/assets/8c6af5b2-c13a-4a45-8cab-80c8ad7be0c9)

This has something to do with this code snipped i believe in modules/character_tools/views/character_tools.tpl.

`{foreach from=$realm.characters item=character}
                        <tr>
                            <td class="col-0">
                                <img src="{$url}application/images/stats/{$character.race}-{$character.gender}.gif">
                            </td>
                            <td class="col-2">
                                <img src="{$url}application/images/stats/{$character.class}.gif" width="20px">
                            </td>
                            <td class="col-3">{$character.name}</td>
                            <td class="col-5">Lv{$character.level}</td>
                            <td>
                                <div class="select_character">
                                    <div class="character store_item">
                                        <section class="character_buttons">
                                            <a href="javascript:void(0)" class="nice_button" onClick="CharacterTools.selectCharacter(this, {$realm.realmId}, {$character.guid}, '{$character.name}')">
                                                Select
                                            </a>
                                        </section>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {/foreach}`

**Comment by Karitoswow** [comment]
"Message me on Discord so we can fully review the issue.  
Discord: shayan8659"

**Comment by TheFrozenThr0ne** [comment]
Fast solved. Thank you.
